export const DEFAULT_WAIT_TIME = 1000;

export const MATCHING_WEIGHTS = {
    id: {
        withKey: { fullMatching: 1, partialMatching: 0.5 },
        withoutKey: { fullMatching: 0.9, partialMatching: 0.45 },
    },
    name: {
        withKey: { fullMatching: 1, partialMatching: 0.8 },
        withoutKey: { fullMatching: 0.9, partialMatching: 0.45 },
    },
    text: {
        withKey: { fullMatching: 1, partialMatching: 0.8 },
        withoutKey: { fullMatching: 0.9, partialMatching: 0.45 },
    },
    value: {
        withKey: { fullMatching: 1, partialMatching: 0.8 },
        withoutKey: { fullMatching: 0.9, partialMatching: 0.45 },
    },
    class: {
        withKey: { fullMatching: 0.9, partialMatching: 0.7 },
        withoutKey: { fullMatching: 0.8, partialMatching: 0.5 },
    },
    placeholder: {
        withKey: { fullMatching: 0.9, partialMatching: 0.6 },
        withoutKey: { fullMatching: 0.8, partialMatching: 0.4 },
    },
    inlineStyle: {
        withKey: { fullMatching: 0.5, partialMatching: 0.3 },
        withoutKey: { fullMatching: 0.4, partialMatching: 0.2 },
    },
    checked: {
        withKey: { fullMatching: 0.5, partialMatching: 0.3 },
        withoutKey: { fullMatching: 0.4, partialMatching: 0.2 },
    },
    html: {
        withKey: { fullMatching: 0.9, partialMatching: 0.3 },
        withoutKey: { fullMatching: 0.8, partialMatching: 0.2 },
    },
    columnName: {
        withKey: { fullMatching: 1, partialMatching: 0.7 },
        withoutKey: { fullMatching: 1, partialMatching: 0.7 },
    },
    columnThHtml: {
        withKey: { fullMatching: 0.8, partialMatching: 0.4 },
        withoutKey: { fullMatching: 0.6, partialMatching: 0.3 },
    },
    parentText: {
        withKey: { fullMatching: 0.3, partialMatching: 0.1 },
        withoutKey: { fullMatching: 0.2, partialMatching: 0.1 },
    },
    label: {
        withKey: { fullMatching: 0.3, partialMatching: 0.1 },
        withoutKey: { fullMatching: 0.2, partialMatching: 0.1 },
    },
};
export const TAGS = {
    input: "input",
    button: "button",
    link: "a",
    text: "span",
    image: "img",
    checkbox: "input[type='checkbox']",
    radio: "input[type='radio']",
    select: "select",
    textarea: "textarea",
    table: "table",
    tr: "tr",
    td: "td",
    th: "th",
    tbody: "tbody",
    thead: "thead",
    tfoot: "tfoot",
    ul: "ul",
    li: "li",
    ol: "ol",
    dl: "dl",
    dt: "dt",
    dd: "dd",
    h1: "h1",
    h2: "h2",
    h3: "h3",
    h4: "h4",
    h5: "h5",
    h6: "h6",
    p: "p",
    div: "div",
    span: "span",
    img: "img",
    a: "a",
    button: "button",
    input: "input",
    select: "select",
    textarea: "textarea",
    form: "form",
    label: "label",
    legend: "legend",
    fieldset: "fieldset",
    table: "table",
    tr: "tr",
    td: "td",
    th: "th",
    tbody: "tbody",
    thead: "thead",
    tfoot: "tfoot",
    ul: "ul",
    i: "i",
    b: "b",
    strong: "strong",
    body: "body",
};
